version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "react-app:1.0.0"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "react-app-tests:1.0.0"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
