name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-docker-demo
          environment_name: React-docker-demo-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-2-730335255488
          region: us-east-2
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB
